name: Build Mod
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: temurin
      - name: Build
        run: |
          wget -q https://services.gradle.org/distributions/gradle-8.11-bin.zip
          unzip -q gradle-8.8-bin.zip
          ./gradle-8.11/bin/gradle build --no-daemon
      - uses: actions/upload-artifact@v4
        with:
          name: musicplayer-jar
          path: build/libs/*.jar
